### ISSUE TITLE
Symfony 3 support

### ISSUE THREAD

**Issue by mcorteel** [usemarkup/addressing#1]
Are you planning on supporting Symfony 3?

**Comment by shieldo** [comment]
Sure - that shouldn't be hard to do. I'll look at this.

**Comment by mcorteel** [comment]
Awesome, I'm really looking forward to this!
Your library would make my life so much easier :)

**Comment by shieldo** [comment]
Let me know if there are other country definitions you need. PRs welcome!

**Comment by shieldo** [comment]
Support now added (any issues, please feed back)
