### ISSUE TITLE
PHP8 compatibility (LightnCandy)

### ISSUE THREAD

**Issue by mcorteel-harel** [usemarkup/addressing#25]
This library is not compatible with PHP 8 due to an issue in LightnCandy, fixed as of [v1.2.6](https://github.com/zordius/lightncandy/releases/tag/v1.2.6). Would it be possible to update the dependency?

**Comment by calumbrodie** [comment]
Hi @mcorteel-harel

I'm about to make this repository private, however I've cloned it to the following location and added the change you suggested.

https://github.com/usemarkup/addressing-public

You can use this fork for now but I suggest that you fork this repo to an alternative location as we will be closing this organisation by the end of February 2021.

- Thanks

**Comment by calumbrodie** [comment]
Edit: Change of plan. Am leaving this (and all our other current repos) public until 28th February 28th, please fork before then
