### ISSUE TITLE
Locality duplicated

### ISSUE THREAD

**Issue by mcorteel** [usemarkup/addressing#7]
The new version comes with a bug for me. I get the `locality` duplicated instead of `postalCode` + `locality`. For example:
> 5, rue du ballon rond
> MARSEILLEMarseille
> France

I have tried to track the problem down, but I'm not sure where it comes from.

**Comment by shieldo** [comment]
Thanks @mcorteel - apologies for the introduced bug - I'll look into it.

**Comment by mcorteel** [comment]
Great!

2017-03-20 11:35 GMT+01:00 Douglas Greenshields <notifications@github.com>:

**Comment by shieldo** [comment]
@mcorteel I've corrected this with https://github.com/usemarkup/addressing/commit/ede98b9bc3b2a1415476668349be4d1e6bde33e2 and released a new 0.2.1 tag - please check that this has fixed the issue for you. Apologies for introducing this error in the new release, and I hope it didn't cause too much inconvenience for you.

**Comment by shieldo** [comment]
(I didn't replicate an issue with the postal code, just the locality - so would be interested to know your feedback.)

**Comment by mcorteel** [comment]
That fixed it, thank you for this very quick fix!

**Comment by shieldo** [comment]
Glad to hear it! 👍
